- hosts: idempotenceserver
  vars_files: 
   - custmizedwebParameter.yml
  tasks:
  - name: "Create Directory"
    file:
     state: directory
     path: "{{dvd_dir}}"

  - name: "Mount CDROM to directory"
    mount:
     src: /dev/sr0
     path: "{{dvd_dir}}"
     state: mounted
     fstype: iso9660

  - name: "Configure Yum"
    yum_repository:
     baseurl: "/{{dvd_dir}}/AppStream"
     name: mydvd1
     description: My dvd
     gpgcheck: no

  - name: "Configure Yum"
    yum_repository:
     baseurl: "/{{dvd_dir}}/BaseOS"
     name: mydvd2
     description: My dvd
     gpgcheck: no

  - name: "Install Httpd"
    package:
     name: httpd
     state: present

  - name: "Create new directory for document root"
    file:
     state: directory
     path: /var/www/mydocumentroot

  - name: Copy web file
    copy: 
     content: "Custmized Web Server with handlers\n"
     dest: /var/www/mydocumentroot/index.html

  - name: "Create configuration file of web server"
    template: 
     dest: /etc/httpd/conf.d/my.conf
     src: /root/Arth/Ansible/Apache_HTTPD/custmizewebser.conf
    notify: restart server

  - name: "Disable firewall for port number"
    firewalld:
      port: "{{port_httpd}}/tcp"
      state: enabled
      permanent: no
      immediate: yes

  handlers:
  - name: restart server
    service:
     name: httpd
     state: restarted
     enabled: no
  
